### ISSUE TITLE
Geo won't install

### ISSUE THREAD

**Issue by chicofish** [biolab/orange3-geo#12] opened 2017-09-22 19:31 UTC
##### Geo version

Using cached Orange3-Geo-0.1.8.tar.gz

##### Orange version

3.5.0
git revision a75eb36

##### Expected behavior
installed add in

##### Actual behavior
error below

##### Additional info (worksheets, data, screenshots, ...)

Windows 10

setuptools have been upgrade, machine restarted but the problem still persists
```text
Collecting Orange3-Geo
Using cached Orange3-Geo-0.1.8.tar.gz
Requirement already satisfied: Orange3 in c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: scikit-learn in c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: pandas in c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: scipy>=0.17 in c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages (from Orange3-Geo)
Collecting shapely (from Orange3-Geo)
Using cached Shapely-1.6.1.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\username\AppData\Local\Temp\1\pip-build-7uepv9kq\shapely\setup.py", line 80, in 
from shapely.buildcfg import geos_version_string, geos_version, 
File "C:\Users\username\AppData\Local\Temp\1\pip-build-7uepv9kq\shapely\shapely_buildcfg.py", line 200, in 
lgeos = CDLL("geos_c.dll")
File "c:\users\username\appdata\local\continuum\anaconda3\lib\ctypes_init.py", line 344, in init
self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\1\pip-build-7uepv9kq\shapely\
```

**Comment by kernc** [comment] 2017-09-22 19:39
Duplicate of https://github.com/biolab/orange3-geo/issues/9.

**Comment by kernc** [comment] 2017-09-22 19:41
Can you try `conda install shapely`.

**Comment by ThirstyGeo** [comment] 2017-09-27 23:58
I am having the same issue and error message

**Comment by astaric** [comment] 2017-10-30 11:58
@chicofish, @ThirstyGeo: The latest version of Orange (3.7.0) can install add-ons using conda (which should solve this problem).

As we are currently beta testing this, it is disabled by default. You can enable it in Options/Settings by checking the box "Install add-ons with conda" in Add-on tab. After you do this, you should be able to install the add-on via the add-ons dialog.

**Comment by chicofish** [comment] 2017-10-30 12:10
Thanks.  I’ll give that a try.

Fred

**Comment by noiseinthestreet** [comment] 2018-01-10 14:15
FYI, I still had to conda install shapely to get Orange3-geo to install without errors by using the add ons menu from Orange 3.8. Here is the error: 

```
Collecting Orange3-Geo
  Using cached Orange3-Geo-0.2.1.tar.gz
Requirement already satisfied: Orange3 in c:\conda\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: scikit-learn in c:\conda\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: pandas in c:\conda\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: scipy>=0.17 in c:\conda\lib\site-packages (from Orange3-Geo)
Collecting shapely (from Orange3-Geo)
  Using cached Shapely-1.6.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DJOHNS~1\AppData\Local\Temp\pip-build-1k2cvx1v\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\DJOHNS~1\AppData\Local\Temp\pip-build-1k2cvx1v\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Conda\lib\ctypes\__init__.py", line 351, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\DJOHNS~1\AppData\Local\Temp\pip-build-1k2cvx1v\shapely\
```

**Comment by kernc** [comment] 2018-01-10 15:44
@noiseinthestreet [Note](https://github.com/biolab/orange3-geo/issues/12#issuecomment-340423201):
> As we are currently beta testing this, it is disabled by default. You can enable it in Options/Settings by checking the box "Install add-ons with conda" in Add-on tab. After you do this, you should be able to install the add-on via the add-ons dialog.

**Comment by astaric** [comment] 2018-03-04 21:36
As of Orange 3.10, installation of add-ons with conda is on by default on windows. If the installation of geo add-on does not work with the latest version of Orange, please open a new issue.

**Closed by astaric** 2018-03-04 21:36 UTC
