### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by poroapor** [biolab/orange3-geo#9] opened 2017-09-05 10:30 UTC
##### Orange version
3.4.4

##### Expected behavior
Install complete

##### Actual behavior
Error is shown

##### Additional info (worksheets, data, screenshots, ...)
```text
Collecting Orange3-Geo
Using cached Orange3-Geo-0.1.8.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Orange3 in c:\users\paniwatk\appdata\local\orange3\python34\lib\site-packages (from Orange3-Geo)
Requirement already satisfied (use --upgrade to upgrade): scikit-learn in c:\users\paniwatk\appdata\local\orange3\python34\lib\site-packages (from Orange3-Geo)
Requirement already satisfied (use --upgrade to upgrade): pandas in c:\users\paniwatk\appdata\local\orange3\python34\lib\site-packages (from Orange3-Geo)
Collecting scipy>=0.17 (from Orange3-Geo)
Using cached scipy-0.19.1.tar.gz
Collecting shapely (from Orange3-Geo)
Using cached Shapely-1.6.1.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "C:\Users\paniwatk\AppData\Local\Temp\pip-build-po9mwode\shapely\setup.py", line 80, in <module>
from shapely._buildcfg import geos_version_string, geos_version, \
File "C:\Users\paniwatk\AppData\Local\Temp\pip-build-po9mwode\shapely\shapely\_buildcfg.py", line 200, in <module>
lgeos = CDLL("geos_c.dll")
File "C:\Users\paniwatk\AppData\Local\Orange3\Python34\lib\ctypes\__init__.py", line 351, in __init__
self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\paniwatk\AppData\Local\Temp\pip-build-po9mwode\shapely\
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command
```

**Comment by kernc** [comment] 2017-09-05 12:28
GEOS library (a sub-dependency) seems to be hard to install on Windos. See: https://github.com/Toblerity/Shapely/issues/343, https://github.com/vilemduha/blendercam/issues/46, https://www.google.com/search?q=geos_c.dll

FWIW, Orange3-Geo has been known to install more readily within Anaconda environments: https://orange.biolab.si/download/windows/

**Comment by kernc** [comment] 2017-11-06 12:42
Duplicate of https://github.com/biolab/orange3-geo/issues/12.

**Closed by kernc** 2017-11-06 12:42 UTC
