### ISSUE TITLE
Geocoding: loading identifier stuck

### ISSUE THREAD

**Issue by stefanuswibowo** [biolab/orange3-geo#73] opened 2019-08-16 06:06 UTC
##### Geo version

0.2.3

##### Orange version

3.22.0

##### Expected behavior
Able to load identifier, similar to link attached:
https://blog.biolab.si/2017/10/13/diving-into-car-registration-data/

##### Actual behavior
the geocoding process stop at 25% thus returning error.

##### Steps to reproduce the behavior
1) Load car.ows from: https://www.dropbox.com/s/p00wpnbmygajgoc/cars.ows?dl=0
2) Load file from: https://www.dropbox.com/s/rb4gx2856f34i47/OsebnaVozila.tab?dl=0
3) Set the pipeline as recomended on: https://blog.biolab.si/2017/10/13/diving-into-car-registration-data/

##### Additional info (worksheets, data, screenshots, ...)
![Capture](https://user-images.githubusercontent.com/35437622/63146855-fb615780-c02e-11e9-94db-dd35475997d2.JPG)

**Comment by ajdapretnar** [comment] 2019-08-20 08:27
I can't reproduce. It works fine for me.

**Comment by stefanuswibowo** [comment] 2019-08-20 09:09
@ajdapretnar can you tell me any configuration that I need to make other than downloading geo from add-ons? many thanks

**Comment by stefanuswibowo** [comment] 2019-08-22 11:50
(base) C:\Users\stefa>orange-canvas
TopologyException: Input geom 1 is invalid: Self-intersection at or near point -7.3461807929999168 57.147935289000046 at -7.3461807929999168 57.147935289000046
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\stefa\Miniconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\stefa\Miniconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\stefa\Miniconda3\lib\site-packages\orangecontrib\geo\mapper.py", line 155, in init
    for admin, centroids in nearest_points.items()}
  File "C:\Users\stefa\Miniconda3\lib\site-packages\orangecontrib\geo\mapper.py", line 155, in <dictcomp>
    for admin, centroids in nearest_points.items()}
  File "sklearn\neighbors\binary_tree.pxi", line 1068, in sklearn.neighbors.kd_tree.BinaryTree.__init__
AttributeError: 'list' object has no attribute 'size'


this is the code when the error occured

**Comment by ajdapretnar** [comment] 2019-08-22 12:07
This doesn't look like an issue of Geocoding, but of Geomap, specifically mapping. @robertcv Could you perhaps take a look?

**Comment by robertcv** [comment] 2019-08-22 12:30
This issue was resolved in #65. Unfortunately, there was no new release of geo add-on since. If you run Orange (and geo add-on) from source, please use master. Else you will have to wait for the new release which will hopefully happen soon.

**Closed by robertcv** 2019-08-22 12:30 UTC
