### ISSUE TITLE
Choropleth: TimeoutError

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#80] opened 2019-10-02 17:43 UTC
##### Geo version

latest

##### Orange version

3.23.0

##### Expected behavior
No error.

##### Actual behavior
Timeout Error probably in Choropleth.

##### Steps to reproduce the behavior
No idea how.

##### Additional info (worksheets, data, screenshots, ...)
This happened at the course. A student's internet connection shut down for a while. We were using Choropleth and Geocoding. The error continually appeared on the screen and it was impossible to get rid of it. Re-connecting to the internet didn't help.
Writing it down for reference.

**Comment by robertcv** [comment] 2019-10-04 07:02
This sometimes happens when JavaScript channel in WebviewWidget is waiting to be processed. It's also relevant to GeoMap. This problem sometimes occurs in tests but a restart normally resolves it as the issue is not consistent. This will be hopefully resolved in the near future when I am finished with the new GeoMap widget that doesn't rely on WebviewWidget and will extend it for Choropleth.

**Comment by ajdapretnar** [comment] 2019-12-05 08:05
Would be fixed with https://github.com/biolab/orange-widget-base/issues/31.

**Comment by janezd** [comment] 2020-04-02 17:29
No longer possible after #89.

**Closed by janezd** 2020-04-02 17:29 UTC
