### ISSUE TITLE
Windows 7 installation

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3-geo#3] opened 2017-07-28 08:40 UTC
##### Orange version
current on Windows 7

##### Expected behavior
Add-on should install via _Options/Add-ons_.

##### Actual behavior
> Collecting Orange3-Geo
> Downloading Orange3-Geo-0.1.8.tar.gz (14.2MB)
> ….
> Collecting shapely (from Orange3-Geo)
> Using cached Shapely-1.5.17.tar.gz
> Complete output from command python setup.py egg_info:
> Traceback (most recent call last):
> File "<string>", line 1, in <module>
> File "C:\Users\user\AppData\Local\Temp\pip-build-k4iz1ise\shapely\setup.py", line 38, in <module>
> from shapely._buildcfg import geos_version_string, geos_version, \
> File "C:\Users\user\AppData\Local\Temp\pip-build-k4iz1ise\shapely\shapely\_buildcfg.py", line 200, in <module>
> lgeos = CDLL("geos.dll")
> File "C:\Python34\lib\ctypes\__init__.py", line 351, in __init__
> self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] The specified module could not be found

**Comment by lorenzoperone** [comment] 2017-08-01 12:07
I've the same issue on Orange 3.4.5 (dmg package) on Mac OS X

> Collecting Orange3-Geo
  Using cached Orange3-Geo-0.1.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
        @_call_aside
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5q/vfs87gnj1b5fy30pp6cp0dfw0000gn/T/pip-build-kpnuhrgv/Orange3-Geo/

**Comment by kernc** [comment] 2017-08-01 13:27
While the error is the same in the sense that Geo add-on doesn't install, the underlying issue (probably https://github.com/pypa/setuptools/issues/885) is definitely not. Please try run in a terminal before retrying:
```bash
/Applications/Orange3.app/Contents/MacOS/python -m pip install -U setuptools==35.0.2 pip==9.0.1
```

**Comment by lorenzoperone** [comment] 2017-08-01 13:29
> Il giorno 01 ago 2017, alle ore 15:27, kernc <notifications@github.com> ha scritto:
> 
> While the error is the same in the sense that Geo add-on doesn't install, the underlying issue (probably pypa/setuptools#885 <https://github.com/pypa/setuptools/issues/885>) is definitely not. Please try run in a terminal before retrying:
> 
> /Applications/Orange3.app/Contents/MacOS/python -m pip install -U setuptools==35.0.2 pip==9.0.1

It works!
Thanks.
l.

**Comment by kernc** [comment] 2017-11-06 12:42
Duplicate of https://github.com/biolab/orange3-geo/issues/12.

**Closed by kernc** 2017-11-06 12:42 UTC
